### ISSUE TITLE
Note. Lib is crashing below API level 24

### ISSUE THREAD

**Issue by msahakyan** [mirrajabi/duration-humanizer#2]
Please mention this lib can be used started from API level 24 and above. 

In the class `DurationHumanizer` you are using function `getOrDefault` which was added in API level 24 and runtimes below it don't have that method.

<img width="654" alt="Screenshot 2021-07-14 at 17 41 52" src="https://user-images.githubusercontent.com/11542701/125651527-c4443b94-9b5d-40b4-b2da-3836e099f561.png">

**Comment by mirrajabi** [comment]
@msahakyan Thanks for reporting this issue.  
I've published v1.0.2 which should fix the problem. can you try it, please?
